{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "logforge.fullname" . }}
  labels:
    {{- include "logforge.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "logforge.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.allowAllIngress }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  {{- else if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress: []
  {{- end }}
  {{- if .Values.networkPolicy.allowAllEgress }}
  egress:
    - {}
  {{- else if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress: []
  {{- end }}
{{- end }}
