{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logforge.configSecretName" . }}
  labels:
    {{- include "logforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.authKeysJSON }}: {{ .Values.secrets.values.authKeysJSON | quote }}
  {{ .Values.secrets.keys.minioAccessKey }}: {{ .Values.secrets.values.minioAccessKey | quote }}
  {{ .Values.secrets.keys.minioSecretKey }}: {{ .Values.secrets.values.minioSecretKey | quote }}
{{- end }}
