apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logforge-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lechuhuuha/log_forge.git
    targetRevision: main
    path: deploy/helm/logforge
    helm:
      valueFiles:
        - ../../env/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
