version: 2
server:
  addr: ":8083"
storage:
  logsDir: "/data/v2/logs"
  analyticsDir: "/data/v2/analytics"
aggregation:
  interval: 30s
ingestion:
  syncOnIngest: true
kafka:
  brokers:
    - kafka:9092
  topic: logs
  groupID: logs-consumer-group
  batchSize: 100
  batchTimeout: 1s
  consumers: 1
  async: false
  requireAllAcks: true
