version: 1
server:
  addr: ":8082"
storage:
  logsDir: "./logs"
  analyticsDir: "./analytics"
aggregation:
  interval: 30s
kafka:
  brokers:
    - localhost:19092
  topic: logs
  groupID: logs-consumer-group
  batchSize: 100
  batchTimeout: 1s
  consumers: 3
  requireAllAcks: true
