apiVersion: k3d.io/v1alpha5 # this will change in the future as we make everything more stable
kind: Simple # internally, we also have a Cluster config, which is not yet available externally
metadata:
  name: logforge-lab # same as the positional NAME in `k3d cluster create NAME` (prefixed as `k3d-`)
servers: 1 # same as `--servers 1`
agents: 1 # same as `--agents 1`
image: rancher/k3s:v1.31.5-k3s1 # same as `--image rancher/k3s:v1.31.5-k3s1`
ports: # same as repeated `--port ...@loadbalancer`
  - port: "8080:80"
    nodeFilters:
      - loadbalancer
  - port: "8443:443"
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs: # same as `--k3s-arg "--disable=traefik@server:0"`
      - arg: --disable=traefik
        nodeFilters:
          - server:0
